server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://sg1db.cufepyonzqt5.ap-northeast-2.rds.amazonaws.com/Spring_FLO?autoReconnect=true # 변경해주세요
    username: admin # 변경해주세요
    password: akrmsk15984 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전